### ISSUE TITLE
Running into an Error

### ISSUE THREAD

**Issue by tgermer** [afaundez/jekyll-favicon#35]
Hi,

I am running into following error.
Are you able to help me with?

```
/Users/tgermer/.rubies/ruby-3.1.0/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:430:in `visit_Psych_Nodes_Alias': Unknown alias: defaults (Psych::BadAlias)
	from /Users/tgermer/.rubies/ruby-3.1.0/lib/ruby/3.1.0/psych/visitors/visitor.rb:30:in `visit'
	from /Users/tgermer/.rubies/ruby-3.1.0/lib/ruby/3.1.0/psych/visitors/visitor.rb:6:in `accept'
	from /Users/tgermer/.rubies/ruby-3.1.0/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:35:in `accept'
	from /Users/tgermer/.rubies/ruby-3.1.0/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:345:in `block in revive_hash'
	from /Users/tgermer/.rubies/ruby-3.1.0/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:343:in `each'
	from /Users/tgermer/.rubies/ruby-3.1.0/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:343:in `each_slice'
	from /Users/tgermer/.rubies/ruby-3.1.0/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:343:in `revive_hash'
	from /Users/tgermer/.rubies/ruby-3.1.0/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:167:in `visit_Psych_Nodes_Mapping'
	from /Users/tgermer/.rubies/ruby-3.1.0/lib/ruby/3.1.0/psych/visitors/visitor.rb:30:in `visit'
	from /Users/tgermer/.rubies/ruby-3.1.0/lib/ruby/3.1.0/psych/visitors/visitor.rb:6:in `accept'
	from /Users/tgermer/.rubies/ruby-3.1.0/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:35:in `accept'
	from /Users/tgermer/.rubies/ruby-3.1.0/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:345:in `block in revive_hash'
	from /Users/tgermer/.rubies/ruby-3.1.0/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:343:in `each'
	from /Users/tgermer/.rubies/ruby-3.1.0/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:343:in `each_slice'
	from /Users/tgermer/.rubies/ruby-3.1.0/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:343:in `revive_hash'
	from /Users/tgermer/.rubies/ruby-3.1.0/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:167:in `visit_Psych_Nodes_Mapping'
	from /Users/tgermer/.rubies/ruby-3.1.0/lib/ruby/3.1.0/psych/visitors/visitor.rb:30:in `visit'
	from /Users/tgermer/.rubies/ruby-3.1.0/lib/ruby/3.1.0/psych/visitors/visitor.rb:6:in `accept'
	from /Users/tgermer/.rubies/ruby-3.1.0/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:35:in `accept'
	from /Users/tgermer/.rubies/ruby-3.1.0/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:345:in `block in revive_hash'
	from /Users/tgermer/.rubies/ruby-3.1.0/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:343:in `each'
	from /Users/tgermer/.rubies/ruby-3.1.0/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:343:in `each_slice'
	from /Users/tgermer/.rubies/ruby-3.1.0/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:343:in `revive_hash'
	from /Users/tgermer/.rubies/ruby-3.1.0/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:167:in `visit_Psych_Nodes_Mapping'
	from /Users/tgermer/.rubies/ruby-3.1.0/lib/ruby/3.1.0/psych/visitors/visitor.rb:30:in `visit'
	from /Users/tgermer/.rubies/ruby-3.1.0/lib/ruby/3.1.0/psych/visitors/visitor.rb:6:in `accept'
	from /Users/tgermer/.rubies/ruby-3.1.0/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:35:in `accept'
	from /Users/tgermer/.rubies/ruby-3.1.0/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:318:in `visit_Psych_Nodes_Document'
	from /Users/tgermer/.rubies/ruby-3.1.0/lib/ruby/3.1.0/psych/visitors/visitor.rb:30:in `visit'
	from /Users/tgermer/.rubies/ruby-3.1.0/lib/ruby/3.1.0/psych/visitors/visitor.rb:6:in `accept'
	from /Users/tgermer/.rubies/ruby-3.1.0/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:35:in `accept'
	from /Users/tgermer/.rubies/ruby-3.1.0/lib/ruby/3.1.0/psych.rb:335:in `safe_load'
	from /Users/tgermer/.rubies/ruby-3.1.0/lib/ruby/3.1.0/psych.rb:370:in `load'
	from /Users/tgermer/.rubies/ruby-3.1.0/lib/ruby/3.1.0/psych.rb:671:in `block in load_file'
	from /Users/tgermer/.rubies/ruby-3.1.0/lib/ruby/3.1.0/psych.rb:670:in `open'
	from /Users/tgermer/.rubies/ruby-3.1.0/lib/ruby/3.1.0/psych.rb:670:in `load_file'
	from /Users/tgermer/.gem/ruby/3.1.0/gems/jekyll-favicon-1.0.0/lib/jekyll/favicon/configuration/defaults.rb:27:in `load_file'
	from /Users/tgermer/.gem/ruby/3.1.0/gems/jekyll-favicon-1.0.0/lib/jekyll/favicon/configuration/defaults.rb:21:in `load_defaults'
	from /Users/tgermer/.gem/ruby/3.1.0/gems/jekyll-favicon-1.0.0/lib/jekyll/favicon/configuration/defaults.rb:16:in `block in included'
	from /Users/tgermer/.gem/ruby/3.1.0/gems/jekyll-favicon-1.0.0/lib/jekyll/favicon/static_file/convertible.rb:18:in `convert'
	from /Users/tgermer/.gem/ruby/3.1.0/gems/jekyll-favicon-1.0.0/lib/jekyll/favicon/static_file/convertible.rb:14:in `convertible?'
	from /Users/tgermer/.gem/ruby/3.1.0/gems/jekyll-favicon-1.0.0/lib/jekyll/favicon/static_graphic_file.rb:13:in `generable?'
	from /Users/tgermer/.gem/ruby/3.1.0/gems/jekyll-favicon-1.0.0/lib/jekyll/favicon/hooks.rb:11:in `block (2 levels) in <top (required)>'
	from /Users/tgermer/.gem/ruby/3.1.0/gems/jekyll-favicon-1.0.0/lib/jekyll/favicon/hooks.rb:9:in `each'
	from /Users/tgermer/.gem/ruby/3.1.0/gems/jekyll-favicon-1.0.0/lib/jekyll/favicon/hooks.rb:9:in `block in <top (required)>'
	from /Users/tgermer/.gem/ruby/3.1.0/gems/jekyll-4.2.1/lib/jekyll/hooks.rb:103:in `block in trigger'
	from /Users/tgermer/.gem/ruby/3.1.0/gems/jekyll-4.2.1/lib/jekyll/hooks.rb:102:in `each'
	from /Users/tgermer/.gem/ruby/3.1.0/gems/jekyll-4.2.1/lib/jekyll/hooks.rb:102:in `trigger'
	from /Users/tgermer/.gem/ruby/3.1.0/gems/jekyll-4.2.1/lib/jekyll/site.rb:38:in `initialize'
	from /Users/tgermer/.gem/ruby/3.1.0/gems/jekyll-4.2.1/lib/jekyll/commands/build.rb:30:in `new'
	from /Users/tgermer/.gem/ruby/3.1.0/gems/jekyll-4.2.1/lib/jekyll/commands/build.rb:30:in `process'
	from /Users/tgermer/.gem/ruby/3.1.0/gems/jekyll-4.2.1/lib/jekyll/command.rb:91:in `block in process_with_graceful_fail'
	from /Users/tgermer/.gem/ruby/3.1.0/gems/jekyll-4.2.1/lib/jekyll/command.rb:91:in `each'
	from /Users/tgermer/.gem/ruby/3.1.0/gems/jekyll-4.2.1/lib/jekyll/command.rb:91:in `process_with_graceful_fail'
	from /Users/tgermer/.gem/ruby/3.1.0/gems/jekyll-4.2.1/lib/jekyll/commands/serve.rb:86:in `block (2 levels) in init_with_program'
	from /Users/tgermer/.gem/ruby/3.1.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
	from /Users/tgermer/.gem/ruby/3.1.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
	from /Users/tgermer/.gem/ruby/3.1.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
	from /Users/tgermer/.gem/ruby/3.1.0/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
	from /Users/tgermer/.gem/ruby/3.1.0/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
	from /Users/tgermer/.gem/ruby/3.1.0/gems/jekyll-4.2.1/exe/jekyll:15:in `<top (required)>'
	from /Users/tgermer/.gem/ruby/3.1.0/bin/jekyll:25:in `load'
	from /Users/tgermer/.gem/ruby/3.1.0/bin/jekyll:25:in `<top (required)>'
	from /Users/tgermer/.rubies/ruby-3.1.0/lib/ruby/site_ruby/3.1.0/bundler/cli/exec.rb:58:in `load'
	from /Users/tgermer/.rubies/ruby-3.1.0/lib/ruby/site_ruby/3.1.0/bundler/cli/exec.rb:58:in `kernel_load'
	from /Users/tgermer/.rubies/ruby-3.1.0/lib/ruby/site_ruby/3.1.0/bundler/cli/exec.rb:23:in `run'
	from /Users/tgermer/.rubies/ruby-3.1.0/lib/ruby/site_ruby/3.1.0/bundler/cli.rb:484:in `exec'
	from /Users/tgermer/.rubies/ruby-3.1.0/lib/ruby/site_ruby/3.1.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /Users/tgermer/.rubies/ruby-3.1.0/lib/ruby/site_ruby/3.1.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/tgermer/.rubies/ruby-3.1.0/lib/ruby/site_ruby/3.1.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /Users/tgermer/.rubies/ruby-3.1.0/lib/ruby/site_ruby/3.1.0/bundler/cli.rb:31:in `dispatch'
	from /Users/tgermer/.rubies/ruby-3.1.0/lib/ruby/site_ruby/3.1.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /Users/tgermer/.rubies/ruby-3.1.0/lib/ruby/site_ruby/3.1.0/bundler/cli.rb:25:in `start'
	from /Users/tgermer/.rubies/ruby-3.1.0/lib/ruby/gems/3.1.0/gems/bundler-2.3.5/exe/bundle:48:in `block in <top (required)>'
	from /Users/tgermer/.rubies/ruby-3.1.0/lib/ruby/site_ruby/3.1.0/bundler/friendly_errors.rb:103:in `with_friendly_errors'
	from /Users/tgermer/.rubies/ruby-3.1.0/lib/ruby/gems/3.1.0/gems/bundler-2.3.5/exe/bundle:36:in `<top (required)>'
	from /Users/tgermer/.gem/ruby/3.1.0/bin/bundle:25:in `load'
	from /Users/tgermer/.gem/ruby/3.1.0/bin/bundle:25:in `<main>'
```

Thank you very much.
Tristan

**Comment by afaundez** [comment]
Hey @tgermer. Thanks for reporting this. Apparently, it's a change in the library Pysch v4 that is causing the issue, and ruby 3.1 has updated the library to 4.0.3.

I'll try to find a workaround for this, but for now, it won't work with ruby 3.1 😩

**Comment by tgermer** [comment]
Thank you very much for your reply @afaundez 
Hopefully you will finde a solution.
Finger crossed.
